# POST http://localhost:2018/api/resume/create-pdf
# Content-Type: application/json

# {
#     "name": "Samyukta",
#     "email": "sam@gmail.com",
#     "education": "UG",
#     "experience": "Beginner",
#     "skills": "AI/ML",
#     "projects": "Done 2 projects on pytorch llama",
#     "contact": 6369442790
# }

# GET http://localhost:2018/api/resume/fetch-pdf
POST http://localhost:2018/auth/register
Content-Type: application/json

{
    "username":"shree1013",
    "email":"21cse131@skcet.ac.in",
    "password":"shree12345",
    "confirmpassword":"shree12345"
}

# GET http://localhost:2018/api/resume/get/shree@gmail.com
